language: node_js
node_js:
  - "12"

before_install:
  - npm i -g npm@6.9.0

jobs:
  include:
      - stage: compile-frontend
        env:
          - NODE_ENV=development
        script: npm run frontend:build
      - stage: unit-tests
        script: npm run test


notifications:
  slack:
    template:
      - "Wahl-O-Mat build *%{result}* for build (<%{build_url}|#%{build_number}>) and commit (<%{compare_url}|%{commit}>) by %{author}."
      - "branch: `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
    rooms: 
      - wahl-o-mat:PvbcfYWht3cfBXXdkuSDdTxN#builds
    on_success: change
    on_failure: always